### ISSUE TITLE
Improve layout of contact list

### ISSUE THREAD

**Issue by phildini** [phildini/logtacts#11]
Hey @paulproteus, I'm thinking of changing the layout of the contact list.

Currently, it looks like:
<img width="1263" alt="screen shot 2016-01-15 at 12 02 53 pm" src="https://cloud.githubusercontent.com/assets/710999/12364335/d578c760-bb82-11e5-9eff-783395237192.png">

I'm thinking of changing it to:
<img width="1277" alt="screen shot 2016-01-15 at 12 22 01 pm" src="https://cloud.githubusercontent.com/assets/710999/12364344/e0b77810-bb82-11e5-8a61-b7c809bf3942.png">

Your thoughts appreciated.

**Comment by paulproteus** [comment]
+0 to new layout

I'm slightly sad that Tags wasted vertical space in the new design. To me,
"Tags" is part of "Search" or "Browse" in which case it belongs somewhere
near "Search" IMHO. Maybe "Search by tag" is a drop-down which adds a tag
chip to the search box.

**Comment by phildini** [comment]
Hmm... I like the idea of off-loading tags "somewhere else".

I would love to do the search-by-tag with a chip in the search box, not sure how to do that yet.

**Comment by paulproteus** [comment]
There's a trick we use in Sandstorm, which is ​you shrink the INPUT and add
a little DIV inside it.

Visit https://www.dropbox.com/referrals or gmail.com's email address field,
and inspect element, and type email addresses in, and watch the width of
the INPUT change.

It's arguably a little excessively slick and frontend-y, but I think it
does massively improve usability.

**Comment by phildini** [comment]
Decided to move tags below contacts, but went with the new design. Closing this issue, but welcome more discussion on layout/look-and-feel either here or in new issues.
