### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by phildini** [phildini/logtacts#17]
> This is an idea issue. This should be a place for discussion, and then individual issues are filed for each outcome of the discussion

So, @neynah has offered to make an icon, which is great! However, before she puts any real work into it, I'd like to seriously consider what the name of this thing should be.

It's currently called Logtacts because it was a mashup of "logging a contact" that made some sense to me and had a domain that was available. I... don't really like the name.

So! Here's a chance to change it, before it gets too serious. 

Some current thoughts:
- It's like a map of your social network and interactions, shareable only with you and people you really trust
- It's an address book
- It's CRM (customer-relationship-managing) software
- It's a tool that potentially makes the emotional labor of building social connections easier, by letting you keep track of it and possibly sending you reminders

Some thoughts on an identity:
- I'm currently obsessed with the idea of giving the tool a persona, like a character (preferably an animal that doesn't need to be gendered and fall into gender stereotypes)
- As the tool gets more-and-more accessible over other interfaces, maybe a character makes sense?
- Something more professional that speaks to the nature of what the software does is also totally fine.

@paulproteus, @neynah, @oboechick - this is your chance to speak up on naming if you'd like. If everyone think Logtacts is a fine name, we'll move forward with that.

**Comment by phildini** [comment]
Hello @neynah! After @oboechick and I talked more about ideas for a logo, we had this kind of quirky idea that we like: One or more otters, either holding little contact books or exchanging information.

It's a bit crazy, but maybe the Logtacts otter can be friends with the Sandstorm Sandcat? :smile_cat: 

(you may wonder, since 'log' is in the current name, why otters and not beavers? Well, the answer is because we like otters more, and think beavers are a bit strange. Cheers!)

**Comment by neynah** [comment]
I like that idea! Funny though we have another [app with otters in their logo](https://apps.sandstorm.io/app/du1nkmp0edheyjq07rm8s1tzr4qs4ut7k24vc2ps0vzm30zp77y0). I guess otters are very well-liked. :D

I'd be happy to style the otter similarly to the sandcat!

This is not the exact same idea but I thought it was cute and worth sharing:
![image](https://cloud.githubusercontent.com/assets/855341/12401421/0c306c5e-bddb-11e5-934c-3b095c6a86ca.png)

**Comment by phildini** [comment]
That is super cute! Also: huh at another app with otters.

(Unrelated, maybe more for @paulproteus: It would be awesome if app store listings had screenshots)

The styling doesn't have to be similar to the sandcat, and I'm happy to let you kind of let your imagination go. Some keywords that might help:

- otters
- books
- contacts
- community
- social graph
- connection
- friends
- family
- reminders
- assistant

**Comment by neynah** [comment]
@phildini Most apps on the market do have screenshots, so you can definitely add screenshots(and we prefer that you do). Thanks for the list of keywords, that's helpful. It may be a week-ish before I get something to you if that's OK. :)

**Comment by phildini** [comment]
That's totally fine, there's no rush on this. I'm just pleased as punch that you're interested! :)

**Comment by paulproteus** [comment]
Available ideas:

- contactotter.com
- ottercontacts.com

Taken ideas:

- otter.club
- otter.co
- otterlog.com

Not-great ideas:

- logotter.com (avail but hard to read)

**Comment by phildini** [comment]
I'm pretty happy with contactotter.com We might go with that.

**Comment by paulproteus** [comment]
The only downside I can now think of is:

"Why should I contact an otter?"

But I think it's OK.

**Comment by phildini** [comment]
"Because otters are amazing!"

No joke I might put this on a faq/landing page with a cute otter video.

**Comment by paulproteus** [comment]
+1​

**Comment by oboechick** [comment]
+2

**Comment by phildini** [comment]
Hey @neynah, we've totally gone forward with ContactOtter as a name. If you're still willing to make some sort of logo for us, I'm pretty willing to upload a sandstorm package to the app store once we have that.

**Comment by neynah** [comment]
That's great. I'm developing concepts this week and will share them here. :D

**Comment by neynah** [comment]
Here's my first set of sketches. They're pretty rough & the photos are terrible but you get the idea. Let me know if you like any of these, if not I can come up with more. :)
![otter-sketches1](https://cloud.githubusercontent.com/assets/855341/12670936/1ea7a228-c621-11e5-91c6-cb41ba566cb1.png)

**Comment by phildini** [comment]
Of the three, the first is my favorite.

Things I like about it:
- includes an otter
- matches the sense of what the product does, by holding a book
- shows the otter doing something (I like the implication that it's
swimming)

Hopefully that helps guide further iterations, feel completely free to ask
me more questions. :)

PJJ
http://philipjohnjames.com

**Comment by neynah** [comment]
Here it is! I'll export the SVGs in the morning if there are no complaints. :)

![image](https://cloud.githubusercontent.com/assets/855341/12943852/da5e87c2-cf98-11e5-858a-a1d3cf4b2047.png)

**Comment by phildini** [comment]
That looks amazing! I like it.

PJJ
http://philipjohnjames.com

**Comment by phildini** [comment]
@neynah, would it be possible to get the SVG of the above so I can put it in the sandstorm app?

**Comment by neynah** [comment]
Yes! I'll get that to you today. :)

**Comment by phildini** [comment]
Closing this for now, to clear the decks a bit.
