### ISSUE TITLE
Search Func

### ISSUE THREAD

**Issue by oboechick** [phildini/logtacts#42]
![screen shot 2016-02-01 at 5 19 27 pm](https://cloud.githubusercontent.com/assets/15068476/12736765/0e513094-c908-11e5-9d02-1c9840ee3d79.png)

I searched for writer and Marion Call came up but there was no writer tag. Is this a bug or am I missing something?

**Comment by phildini** [comment]
The search searches over a bunch of stuff in the contact, and tag is part of that. In her "Notes" field, it says "Awesome singer-songwriter", so it was matching on that.
