### ISSUE TITLE
Invite

### ISSUE THREAD

**Issue by oboechick** [phildini/logtacts#43]
So I thought that the invite was to invite people to Contact Otter not share my contact list.

**Comment by phildini** [comment]
@oboechick should this be a separate screen or an option on the existing invite screen?

**Comment by oboechick** [comment]
I'm not sure I understand your question. What I want is a here is how I share my address book and a separate here is how to invite people to create their own button. Right now your invite button refers to the first part, not the second. Does that answer your question?
