### ISSUE TITLE
Calendar Integration

### ISSUE THREAD

**Issue by phildini** [phildini/logtacts#45]
As I feel that ContactOtter is more useful the more places it connects, I feel like some kind of calendar integration might be useful.

I think @clach04 has more ideas here, or a specific use-case?

**Comment by clach04** [comment]
From chatting with a possible user, there was some interest in scheduling a future contact (and or scheduling a repeating contact). Not quote sure on work flow (e.g. confirm contact happened?). Or on reporting, e.g. show future contacts that need to happen, and who will be making that contact.

**Comment by phildini** [comment]
Would having a link to create a google calendar event work here? Should ContactOtter try to auto-schedule by having access to your calendar? Option 1 is simpler and less invasive, option 2 might be the better user experiencer?

**Comment by clach04** [comment]
Option 1 sounds good. Meetup.com's calendar widget works really well (when you know its there). E.g. http://www.meetup.com/Jenkins-online-meetup/events/230154841/

The "Export" thing is a drop down with export to Outlook, iCal, Google, and Yahoo. I use the Google one a lot, I think I've tried the Outlook one.
