### ISSUE TITLE
Add Work Phone to Contact info

### ISSUE THREAD

**Issue by oboechick** [phildini/logtacts#48]
You have Cell and Home but not work.

**Comment by phildini** [comment]
Yeah... this relates to #6, in that you should basically be able to say what fields you want available on a book level. Maybe I'll just keep adding fields for now? @paulproteus' thoughts on schema appreciated.

**Comment by paulproteus** [comment]
For now, I would say, keep adding fields.

For the future, I would say:

You're probably going to want some many2many mess behind the scenes. Just
make sure the queries are performant.
