### ISSUE TITLE
Search should try and keep indexes 'hot'

### ISSUE THREAD

**Issue by phildini** [phildini/logtacts#5]
This is more something for @paulproteus, but I think the idea of keeping the indexes always accurate, without incurring much performance hit, is :100:

**Comment by paulproteus** [comment]
: D

**Comment by phildini** [comment]
This might help: http://django-haystack.readthedocs.org/en/latest/best_practices.html#real-time-search

**Comment by paulproteus** [comment]
https://django-haystack.readthedocs.org/en/latest/signal_processors.html#realtime-realtimesignalprocessor

Amazing. I would suggest enabling this on Sandstorm, then. I think it's OK
to slightly slow down request/response on Sandstorm for this sort of thing,
fwiw.

**Comment by phildini** [comment]
Go ahead. 😄
