### ISSUE TITLE
on sandstorm: Setting a birthdate causes "Server Error (500)"

### ISSUE THREAD

**Issue by kentonv** [phildini/logtacts#52]
When I try to save a contact with a birthdate, I get an error. The server debug log says:

    {"levelname": "ERROR", "message": "Internal Server Error: /new", "status_code": 500, "module": "base", "name": "django.request", "pathname": "/opt/app/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", "asctime": "2016-02-22 00:31:15,847", "request": "<WSGIRequest: POST '/new'>"}
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/handlers.py", line 863, in emit
        self.socket.sendto(msg, self.address)
    gaierror: [Errno -3] Temporary failure in name resolution

**Comment by paulproteus** [comment]
Note that this might be a Sandstorm-specific issue, so for now, adjusting bug title accordingly. @kentonv thanks for filing this!

**Comment by keybits** [comment]
I get the same error when adding a 'log' entry to a contact.

(Nice app BTW :-) Been looking for something like this for a while.)

**Comment by phildini** [comment]
This is fixed in version 0.0.2 of the sandstorm package, which is live now! @keybits, your bug was fixed at the same time.

**Comment by keybits** [comment]
Thanks for the fix :-)
