### ISSUE TITLE
Feature request: Allow different fields for social networks and such

### ISSUE THREAD

**Issue by ocdtrekkie** [phildini/logtacts#53]
I don't tumblr. I barely tweet. I do use Google+, and on rare occasion Facebook. I've been playing with Diaspora. I kinda feel like this contact setup shoehorns me a bit. And if I don't use a social network (like tumblr), I'd rather be rid of the field entirely, across my entire grain.

So it'd be really awesome if we could define which networks we want to show here or something similar.

**Comment by phildini** [comment]
Relates to #6, #41, #48.

**Comment by ocdtrekkie** [comment]
Yeah, I feel kinda redundant now. I'm super excited to see contact managers for Sandstorm though! My Google Contacts is probably one of my most critical still-on-Google things.

**Comment by phildini** [comment]
@ocdtrekkie this has now been added to the sandstorm package. Let me know if this solves your problem, and if you could leave a review on sandstorm that would be amazing.

**Comment by ocdtrekkie** [comment]
Thanks, I'll take another look soon.
