### ISSUE TITLE
on Sandstorm: Provide a way to get back to the root view

### ISSUE THREAD

**Issue by paulproteus** [phildini/logtacts#56]
This might make sense on non-Sandstorm too, not sure yet.

One semi-standard thing to do is to have a logo link in the top-left.

**Comment by phildini** [comment]
I don't understand. The logo in the top left is a link back to the root view?

**Comment by phildini** [comment]
There is now no case where there isn't a logo in the top left at the top of the page, so marking this closed.

**Comment by paulproteus** [comment]
Thanks!
