### ISSUE TITLE
on Sandstorm: "Invite others" could trigger Sandstorm sharing UI

### ISSUE THREAD

**Issue by paulproteus** [phildini/logtacts#57]
Right now, instead, it triggers an error 500!

See also "startsharing" except curiously https://docs.sandstorm.io/en/latest/search.html?q=startsharing is no results found, so I guess I should document this within Sandstorm.

**Comment by phildini** [comment]
How are you finding this? All the links are hidden if sandstorm is detected.

**Comment by eyedarts** [comment]
In my grain, whenever my browser window is less than 1040 width, I see the following links:

Settings
Logout
Invite Others
Give Feedback

I'm not advanced at this, but is the duplication listing the menu items in `base.html` necessary?

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li class="dropdown hidden-xs hidden-sm">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello {% if user.first_name %}{{ user.first_name }}{% else %}{{ user.username }}{% endif %}!<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            {% if user.is_staff %}
                            <li><a href="/admin/">Admin</a></li>
                            {% endif %}
                            {% if not SANDSTORM %}
                            <li><a href="/u/">Settings</a></li>
                            <li><a href="/logout/">Logout</a></li>
                            <li><a href="{% url "create-invite" %}">Invite others</a></li>
                            {% endif %}
                            <li><a href="http://goo.gl/forms/npAgYliQM8" target="_blank">Give Feedback</a><li>
                        </ul>
                    </li>
                    {% endif %}
                    {% if user.is_staff %}
                    <li class="visible-sm visible-xs"><a href="/admin/">Admin</a></li>
                    {% endif %}
                    <li class="visible-sm visible-xs"><a href="/u/">Settings</a></li>
                    <li class="visible-sm visible-xs"><a href="/logout/">Logout</a></li>
                    <li class="visible-sm visible-xs"><a href="{% url "create-invite" %}">Invite others</a></li>
                    <li class="visible-sm visible-xs"><a href="http://goo.gl/forms/npAgYliQM8">Give Feedback</a><li>
                </ul>

If it is, maybe add another `{% if not SANDSTORM %}` block to that second menu listing code block:

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li class="dropdown hidden-xs hidden-sm">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello {% if user.first_name %}{{ user.first_name }}{% else %}{{ user.username }}{% endif %}!<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            {% if user.is_staff %}
                            <li><a href="/admin/">Admin</a></li>
                            {% endif %}
                            {% if not SANDSTORM %}
                            <li><a href="/u/">Settings</a></li>
                            <li><a href="/logout/">Logout</a></li>
                            <li><a href="{% url "create-invite" %}">Invite others</a></li>
                            {% endif %}
                            <li><a href="http://goo.gl/forms/npAgYliQM8" target="_blank">Give Feedback</a><li>
                        </ul>
                    </li>
                    {% endif %}
                    {% if user.is_staff %}
                    <li class="visible-sm visible-xs"><a href="/admin/">Admin</a></li>
                    {% if not SANDSTORM %}
                    <li class="visible-sm visible-xs"><a href="/u/">Settings</a></li>
                    <li class="visible-sm visible-xs"><a href="/logout/">Logout</a></li>
                    <li class="visible-sm visible-xs"><a href="{% url "create-invite" %}">Invite others</a></li>
                    {% endif %}
                    <li class="visible-sm visible-xs"><a href="http://goo.gl/forms/npAgYliQM8">Give Feedback</a><li>
                </ul>

**Comment by phildini** [comment]
@eyedarts your suggestion seems totally reasonable. If you want to file a PR, please do! If not, I'll get to it when I can.

**Comment by phildini** [comment]
@eyedarts I ended up grabbing this because there were some other bugs I was fixing, but I'm still very interested in other bugs being fixed if you're interested. Happy to help in any way.

**Comment by eyedarts** [comment]
@phildini Ok, cool. Thanks for doing this!
