### ISSUE TITLE
Suggestion: Rename "Add Log"

### ISSUE THREAD

**Issue by paulproteus** [phildini/logtacts#58]
Possible alternatives:

- "Add a note about a time you contacted them"

- "Log a time you contacted them"

**Comment by phildini** [comment]
So I'm certainly willing to change this to something more useful, I don't really like either of those suggestions. Mainly because they're too verbose. If you can think of a phrasing that's 1-3 words that you think is more semantic, happy to change it.

**Comment by phildini** [comment]
I'm going to close this for now, but I'm totally willing to re-open if we want to think about more suggestions.
