### ISSUE TITLE
Sandstorm - Allow Export of All Fields

### ISSUE THREAD

**Issue by eyedarts** [phildini/logtacts#60]
#### What you expected to happen

Click on "More" drop down box and have the option to export all fields from selected contacts.
#### What actually happened

Currently, there's only the option to export "Emails" or "Addresses."
##### Is this on sandstorm?

(yes)

Does this involve creating a `class ExportAllFieldsView(BookOwnerMixin, TemplateView)` class in `contact_views.py` and a new `export_all_fields.html` template? If so, I may be able to help with that.

**Comment by phildini** [comment]
You're totally on the right track, if you want full-export as csv. If you want a "data dump", there's a json export under "Settings".

If full-csv export is something you want, feel free to add a PR, and let me know if you have any questions.

**Comment by phildini** [comment]
closing this, as the sandstorm app is currently not supported. Hoping I get back to it some day.
