### ISSUE TITLE
Feature Request: View logs / notes for all contacts on one screen in date order

### ISSUE THREAD

**Issue by keybits** [phildini/logtacts#61]
It would be great to have a summary screen where you can view log entries / notes for all contacts in chronological order.

Perhaps there could be an option to filter by log / note type.

Then I could see at a glance all the people I phoned last week. Or all the people who visited last month.

**Comment by phildini** [comment]
That's a super neat idea. Thanks!

**Comment by phildini** [comment]
Hey there! this is now done.
