### ISSUE TITLE
Sandstorm apps shouldn't run Google Analytics code

### ISSUE THREAD

**Issue by ocdtrekkie** [phildini/logtacts#64]
#### What you expected to happen

I was kinda surprised to see my Privacy Badger extension light up when I was on a Sandstorm app. While client-side sandboxing isn't currently done in Sandstorm, external calls like this are supposed to be blocked before 1.0.
#### What actually happened

Privacy Badger found information was being sent to Google Analytics
#### Steps to reproduce
- Install Privacy Badger
- Navigate to a Contact Otter grain
##### Is this on sandstorm?

Yes

**Comment by ocdtrekkie** [comment]
App also seems to hit:

logtacts.s3.amazon.com - What is this used for?
maxcdn.bootstrapcdn.com - Code that could be in-app?
ajax.googleapis.com - Code that could be in-app?
secure.gravatar.com - Presumably to generate icons... what info is sent though?

**Comment by phildini** [comment]
Hey, thanks for leaving the feedback. We'll turn off GA for sandstorm, and I think the rest of the assets could be hosted locally. Not sure how to get rid of gravatar, do you have suggestions that would be easy to implement?

**Comment by ocdtrekkie** [comment]
I honestly kinda assumed, not being a Gravatar user (that I'm aware of), that it was similar to identicon.js? Their website suggests that they are actual photo avatars as people use them elsewhere around the Internet. Do you find most of your contacts have their avatars on Gravatar?

**Comment by phildini** [comment]
Closing this as the sandstorm app is currently not supported. :/ I has a sad, and hopefully will get back to it some day.
