### ISSUE TITLE
Static assets should auto-compile and update.

### ISSUE THREAD

**Issue by phildini** [phildini/logtacts#76]
Not sure how to make this happen safely, but we should be referencing new versions of assets when they're pushed to clear the cache.

**Comment by paulproteus** [comment]
My usual preference on these things is to refer to assets by a name that
indicates the build, or alternatively, indicates their content. There are a
variety of open source Django packages that enable this.

**Comment by phildini** [comment]
@paulproteus Can you name some? Finding examples that you like would be
really helpful, and I agree about including build or commit info.

PJJ
http://philipjohnjames.com

**Comment by phildini** [comment]
I ended up making this work by using whitenoise and django's built-in static handling. Good enough for now.
