### ISSUE TITLE
Create Sandstorm package

### ISSUE THREAD

**Issue by paulproteus** [phildini/logtacts#8]
The Sandstorm package would presumably only support one "Book". People would be able to make more "books" by creating more grains of logtacts within Sandstorm.

I'll almost definitely be the person who does this, but worth filing an issue.

**Comment by paulproteus** [comment]
Sub-tasks:

- Integrate in some reasonable way with Django authentication

- Figure out what the name of an instance is "New Logtacts contact list"? "New Logtacts collection"? "New Logtacts someThing" anyway

- Come up with a logo (or ask @neynah to make one)

**Comment by neynah** [comment]
@paulproteus I'd be happy to!

**Comment by phildini** [comment]
Whoa. A logo would be real great, @neynah! FWIW, I will happily take any and all design feedback, I just always feel super guilty asking people for it. Feel free to file design-related issues or PRs, and I'm happy to chat in person or over google hangout if that would be helpful.

**Comment by neynah** [comment]
@phildini Do you have any ideas in mind for the logo that I can work off of? :)

**Comment by phildini** [comment]
@neynah I made #17 as a place to discuss branding. My primary thoughts right now are that 'logtacts' isn't my favorite name, and this could be a great chance to choose a better one.

Sorry to basically ask you to 'hurry up and wait' - if you're still interested but the time is _now_, then I would say something that's more generically dealing with the ideas of contacts, books, social networks, and connections.

**Comment by phildini** [comment]
I'm also going to suggest we move further discussion to the other issue, to keep this one clear for sandstorm-packaging issues.

**Comment by phildini** [comment]
Hey @paulproteus, how are you planning on translating sandstorm auth to django auth?

**Comment by paulproteus** [comment]
Presumably I'm going to have to write that thing that you said you wanted,
which is a django auth package​ that receives Sandstorm headers in and
creates Django user model instnaces in the database out.

**Comment by phildini** [comment]
That is totally a thing I would be happy to pair with you on, if you want to grab some in-person time.

**Comment by paulproteus** [comment]
Ooh, good to know.​

**Comment by phildini** [comment]
Yeah, basically my thought is that the 'canonical' implementation for
Logtacts will be at logtacts.com (or whatever), but that people who want
full privacy will be directed to the sandstorm package. Along those lines,
I would like the sandstorm package to be a first-class citizen of the
logtacts world, so I want to see it succeed.

PJJ
http://philipjohnjames.com

**Comment by paulproteus** [comment]
+1 see emails to schedule!!

**Comment by phildini** [comment]
Hey! This can be closed now. Super exciting!
